### ISSUE TITLE
Highlighter plugin needs to handle undefined opts.yaxis better

### ISSUE THREAD

**Issue by johanbove** [svandecappelle/jQPlot#13]
Currently experiencing the issue that opts.yaxis is not defined and therefore the highlighter is not running.
The issue is on line 241:

```
if (opts.yaxis.formatter){
```

should be:

```
if (opts.yaxis && opts.yaxis.formatter){
```

**Comment by svandecappelle** [comment]
You shoud commit builded distribution files on your merge.
```npm install```
```grunt```

It will regenerate the distribution files into the dist directory.

**Comment by johanbove** [comment]
OK, will do this on next build.

On Tue, Aug 4, 2015 at 5:08 PM, Vandecappelle <notifications@github.com>
wrote:

> You shoud commit builded distribution files on your merge.
> npm install
>
>
> It will regenerate the distribution files into the dist directory.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/svandecappelle/jQPlot/issues/13#issuecomment-127644444>
> .
>



-- 
Johan

--
http://johanbove.info

**Comment by svandecappelle** [comment]
Forget it: if lots of merges request are pending it could cause lots of conflicts.

Sry was my mistake to comment this.

**Comment by johanbove** [comment]
Yeah, was actually thinking that the "dist" folder should be in the .gitignore folder. Perhaps we should create a "release" branch?

**Comment by johanbove** [comment]
Closing the ticket since original issue was done.
