### ISSUE TITLE
Fix JSlint errors in jqplot.core.js

### ISSUE THREAD

**Issue by johanbove** [svandecappelle/jQPlot#16]
I would like to start with clearing out the JSlint Problems with the core file `src\core\jqplot.core.js`

I'm using these settings:

```
/*jslint browser: true, plusplus: true, nomen: true, white: false */
/*global $, console, jqPlot */
```

Current tasks:
- [x] Start using JSLint to check for code issues. :see_no_evil: 
- [x] Move methods out of the `JqPlot()` constructor function.
- [x] Finish more JSLint issues.
- [x] Refactor huge function `checkIntersection()`.
 - Would like to separate the main switch on ``s.renderer.constructor`` to use separate sub functions for each case.
- [x] Refactor huge `JqPlot.prototype.draw()`.

**Comment by johanbove** [comment]
Currently work in progress; See my branch: https://github.com/johanbove/jQPlot/tree/jqplotcore_cleanup
Also adding tests to check my changes.

**Comment by svandecappelle** [comment]
Question: Can we ignore this jslint error (and how) ?  : 
* Combine this with the previous 'var' statement

**Comment by johanbove** [comment]
Well, actually with JsLint it is not possible to switch to allow multiple `var'`statements. I do understand why you are asking this.

We should have a consistent way of declaring variables and I agree with Douglas Crockford's idea that it is good practice to declare variables as [proposed by JsLint](http://javascript.crockford.com/code.html) with a single var and comma separate them.

I actually use [this style](http://benalman.com/news/2012/05/multiple-var-statements-javascript/#comment-518992608) as proposed by "Cowboy" Ben Alman, in more complicated functions:

>  if you really wanted to write your code as JavaScript would interpret it, you'd hoist all VariableDeclarations to the top of the execution context, per the EcmaScript 5 spec, section 10.5, like so.
```
function blah(e) {
  // Hoisted VariableDeclarations.
  var fizz, buzz, bar;
  // Assignments, as-needed.
  fizz = "hello world";
  buzz = 42;
  bar = {
    bop: 'baz'
  };
}
```

So since I learned about this I always used a single comma separated `var´ statement to group the function variables in.

Most important is to declare all the `var` statements at the top of the function, cf variable hoisting.

More information: <https://jslinterrors.com/combine-this-with-the-previous-var-statement>

**Comment by svandecappelle** [comment]
Thanks for the documentation and the good practices. =)

**Comment by johanbove** [comment]
Closing this issue for now since general optimizations are essentially done.
When I see some more optimization I'll create separate issues for now on.
Thanks for the merge!
