### ISSUE TITLE
Fix JSlint errors in plugins files

### ISSUE THREAD

**Issue by svandecappelle** [svandecappelle/jQPlot#18]

**Comment by johanbove** [comment]
Making a lot of changes to the files, so it might best if we coordinated which files we handle at a time. Better not have us work on the same files or it's going to be a merging hell.

**Comment by svandecappelle** [comment]
Agree with that: I created issues for each plugins.
When we work on jslint for a plugin: assign to yourself.

**Comment by johanbove** [comment]
Great. Goog to see the issues created. Thing is that I can't assign these issues to me since this repo is in your personal Github account if you don't add me as a "collaborator" first. See [this Github help](https://help.github.com/articles/adding-collaborators-to-a-personal-repository/) document.
